project_id = "fkwtximvrcxmccoafncq"

[functions.realtime-token]
verify_jwt = false

[functions.cancel-reservation]
verify_jwt = false

[functions.edit-reservation]
verify_jwt = false

[functions.reservation-chatbot]
verify_jwt = false
